# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Audit
version:      0.02
version_from: lib/Class/DBI/Audit.pm
installdirs:  site
requires:
    Class::DBI:                    0
    mixin:                         0
    SQL::Abstract:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
